version: '1.0'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  node:
    build: ./node
    ports:
      - '3000:3000'